### ISSUE TITLE
Confirm that vmsDlOpen is working...

### ISSUE THREAD

**Issue by tesneddon** [endlesssoftware/sqlite3#18]
Test the LIB$FIS stuff and make sure it works correctly.

**Comment by tonymcg27** [comment]
G'day Tim,

The short answer is "it's not working".

The long answer... I've been toying with the idea of using RMS indexed files to setup a tiny database but after reading a few recent postings on Comp.OS.VMS that discussed SQLite I thought I'd give it a try. So glad I did, it's great.
I downloaded your source code and it compiled so easily. Thank you so much for all your hard work to make it build on VMS.
Then I started to get adventurous, I wanted to be able to use values of DCL global/local symbols in my queries, similar to Rdb's "GET ENVIRONMENT" capability. I knocked up some code to do the trick but it wouldn't ".load", I was getting "%LIB-F-INVARG, invalid argument(s)" errors.
I tracked it down to the call to LIB$FIND_IMAGE_SYMBOL in the vmsDlSym function in the OS_VMS.C file. The "flags" argument was being passed by Reference, when it ought to be by Value. Now it works perfectly. Sooo happy.
I have some sample code for the Extension shareable image that I'm happy to send to you. Maybe we need a "contrib" subdirectory on your sqlite3 tree.

Thanks for making a great tool available to the VMS community,
  Tony
  (Melbourne, Australia)

**Comment by tesneddon** [comment]
Hi Tony,

Thanks so much for the compliments.  I haven't been a reader of c.o.v for a long time now.  There is so little useful information on there, it's not worth my time.

I'm glad that it suited your needs and thanks for fixing the bug in loadable modules.  I would certainly be very interested in anything you would like to contribute.  I think a VMS-specific example of a loadable module would be an excellent addition.

Feel free to post your code here or join the SQLite for OpenVMS mailing list (see the wiki) and post it there.

Regards, Tim.
(Perth, Australia)
